### ISSUE TITLE
Странные ошибки при установке

### ISSUE THREAD

**Issue by sashabeep** [ZeeyN/evocms-minifier#1]
Возможно, это к пакету не относится
```
artisan package:installrequire zeeyn/evocms-minifier '^1.1.1'
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /home/.../core/vendor/composer/composer/src/Composer/DependencyResolver/Solver.php on line 223
Fatal error: Uncaught ErrorException: Undefined index: HTTP_HOST in /home/.../core/src/ExceptionHandler.php:175
Stack trace:
#0 /home/.../core/src/ExceptionHandler.php(175): Composer\Util\ErrorHandler::handle(8, 'Undefined index...', '/home/.../w...', 175, Array)
#1 /home/.../core/src/ExceptionHandler.php(510): EvolutionCMS\ExceptionHandler->messageQuit('Allowed memory ...', '', true, '', '/home/.../w...', '', '', 223, '', Array)
#2 /home/.../core/src/ExceptionHandler.php(46): EvolutionCMS\ExceptionHandler->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 [internal function]: EvolutionCMS\ExceptionHandler->handleShutdown()
#4 {main}
  thrown in /home/.../core/src/ExceptionHandler.php on line 175
```
Но после выполнения ```composer upd```

```
Package operations: 3 installs, 0 updates, 0 removals
  - Installing matthiasmullie/path-converter (1.1.2): Downloading (100%)         
  - Installing matthiasmullie/minify (1.3.62): Downloading (100%)         
  - Installing zeeyn/evocms-minifier (v1.1.1): Downloading (100%)
```

И пакет работает.
Что происходит не так?

**Comment by ZeeyN** [comment]
Какая версия php?
Ну и сколько памяти есть на сервере?

**Comment by sashabeep** [comment]
7.4.1
Памяти хз, это шаред. Но учитывая, что он пытается выделить 4096 байт - это странно. 4096 точно есть

**Comment by ZeeyN** [comment]
У вас получилось так: на первую команду не хватило памяти, при этом файлы composer-а изменились, на вторую команду памяти хватило, и оно всё подтянуло в соответствии с файлами. Проблема не в пакете.
