### ISSUE TITLE
Could not perform composer update after update to to 2.0.2

### ISSUE THREAD

**Issue by sashabeep** [ZeeyN/evocms-minifier#3]
```
composer upd
Installing matthiasmullie/path-converter (1.1.3): Downloading (100%)         
  - Installing matthiasmullie/minify (1.3.63): Downloading (100%)         
    Skipped installation of bin bin/minifycss for package matthiasmullie/minify: name conflicts with an existing file
    Skipped installation of bin bin/minifyjs for package matthiasmullie/minify: name conflicts with an existing file
  - Installing zeeyn/evocms-minifier (v1.1.2): Downloading (100%)         
...
matthiasmullie/minify suggests installing psr/cache-implementation (Cache implementation to use with Minify::cache)
```

**Comment by ZeeyN** [comment]
Did you tried to fully delete package and install it again?

**Comment by sashabeep** [comment]
@ZeeyN looks like it was memory issue. With compose_memory_limit = -1 all the packages updating correctly instead of downgrading

**Comment by ZeeyN** [comment]
@sashabeep that pretty good. But careful with 2.0.2 version of evo and 1.2.0 of minifier, i'm trying to take care of all conflicts that can appear. On vrsion 2.0.0 all works good.

**Comment by sashabeep** [comment]
Reopen.
Не могу обновить сайты
Сыпет кучу ошибок
Как его удалить вручную, в конце-концов. после composer upd сайт становится нерабочим полностью

На внешке
```
Fatal error: Uncaught ReflectionException: Class blade.compiler does not exist in /home/.../core/vendor/illuminate/container/Container.php:804 Stack trace:
#0 /home/.../core/vendor/illuminate/container/Container.php(804): ReflectionClass->__construct('blade.compiler')
#1 /home/.../core/vendor/illuminate/container/Container.php(682): Illuminate\Container\Container->build('blade.compiler')
#2 /home/.../core/vendor/illuminate/container/Container.php(630): Illuminate\Container\Container->resolve('blade.compiler', Array)
#3 /home/.../core/src/AbstractLaravel.php(464): Illuminate\Container\Container->make('blade.compiler', Array)
#4 /home/.../core/vendor/illuminate/container/Container.php(1246): EvolutionCMS\AbstractLaravel->make('blade.compiler')
#5 /home/.../core/vendor/illuminate/support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet('blade.compiler')
#6 /home/... in /home/.../core/vendor/illuminate/container/Container.php on line 806
```

В консоли
```
php artisan package:discover

Fatal error: Uncaught ReflectionException: Class blade.compiler does not exist in /home/.../core/vendor/illuminate/container/Container.php:804
Stack trace:
#0 /home/.../core/vendor/illuminate/container/Container.php(804): ReflectionClass->__construct('blade.compiler')
#1 /home/.../core/vendor/illuminate/container/Container.php(682): Illuminate\Container\Container->build('blade.compiler')
#2 /home/.../core/vendor/illuminate/container/Container.php(630): Illuminate\Container\Container->resolve('blade.compiler', Array)
#3 /home/.../core/src/AbstractLaravel.php(464): Illuminate\Container\Container->make('blade.compiler', Array)
#4 /home/.../core/vendor/illuminate/container/Container.php(1246): EvolutionCMS\AbstractLaravel->make('blade.compiler')
#5 /home/.../core/vendor/illuminate/support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet('blade.compiler')
#6 /home/... in /home/.../core/vendor/illuminate/container/Container.php on line 806
```

```
composer remove zeeyn/evocms-minifier
zeeyn/evocms-minifier is not required in your composer.json and has not been removed
```

**Comment by sashabeep** [comment]
в /manager также зайти невозможно из-за белого экрана с той же ошибкой

**Comment by sashabeep** [comment]
@ZeeyN Any info needed :)

**Comment by ZeeyN** [comment]
@sashabeep В ево был косяк с композером. Если после composer upd вылазит ошибка какая либо, пробуйте обновить через composer update.

Сейчас гляну что да как и отпишу.

**Comment by sashabeep** [comment]
Да просто есть уже установленная 2.0.2 с предыдущей версией minifier. Без вчерашних исправлений в composer.json. Делаю там composer update и всё что выше описал. Всё, после этого сайт нерабочий полностью, только откат

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 23 updates, 0 removals
  - Removing wikimedia/composer-merge-plugin (dev-master 73e4ed4)
  - Installing wikimedia/composer-merge-plugin (dev-master 18dbae0): Loading from cache
  - Updating doctrine/dbal (v2.10.1 => 2.10.2): Loading from cache
  - Updating symfony/polyfill-ctype (v1.14.0 => v1.15.0): Loading from cache
  - Updating phpoption/phpoption (1.7.2 => 1.7.3): Loading from cache
  - Updating vlucas/phpdotenv (v3.6.1 => v3.6.3): Loading from cache
  - Updating league/flysystem (1.0.66 => 1.0.67): Loading from cache
  - Updating tracy/tracy (v2.7.3 => v2.7.4): Loading from cache
  - Updating symfony/process (v4.4.5 => v4.4.7): Loading from cache
  - Updating zeeyn/evocms-minifier (v1.1.2 => v1.2.0): Loading from cache
  - Updating composer/ca-bundle (1.2.6 => 1.2.7): Loading from cache
  - Updating symfony/polyfill-php73 (v1.14.0 => v1.15.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.14.0 => v1.15.0): Loading from cache
  - Updating symfony/console (v4.4.5 => v4.4.7): Loading from cache
  - Updating symfony/filesystem (v5.0.5 => v5.0.7): Loading from cache
  - Updating symfony/finder (v4.4.5 => v4.4.7): Loading from cache
  - Updating composer/semver (1.5.1 => 2.0.0): Loading from cache
  - Updating illuminate/contracts (v6.18.2 => v6.18.10): Loading from cache
  - Updating symfony/translation (v5.0.5 => v5.0.7): Loading from cache
  - Updating nesbot/carbon (2.31.0 => 2.32.2): Loading from cache
  - Updating psr/log (1.1.2 => 1.1.3): Loading from cache
  - Updating symfony/debug (v4.4.5 => v4.4.7): Loading from cache
  - Installing react/promise (v2.7.1): Loading from cache
  - Removing composer/composer (dev-master 3405781)
  - Installing composer/composer (dev-master d173af2): Downloading (100%)         
Writing lock file
Generating autoload files
> @php artisan package:discover

Fatal error: Uncaught ReflectionException: Class blade.compiler does not exist in /home/.../core/vendor/illuminate/container/Container.php:804
Stack trace:
#0 /home/.../core/vendor/illuminate/container/Container.php(804): ReflectionClass->__construct('blade.compiler')
#1 /home/.../core/vendor/illuminate/container/Container.php(682): Illuminate\Container\Container->build('blade.compiler')
#2 /home/.../core/vendor/illuminate/container/Container.php(630): Illuminate\Container\Container->resolve('blade.compiler', Array)
#3 /home/.../core/src/AbstractLaravel.php(464): Illuminate\Container\Container->make('blade.compiler', Array)
#4 /home/.../core/vendor/illuminate/container/Container.php(1246): EvolutionCMS\AbstractLaravel->make('blade.compiler')
#5 /home/.../core/vendor/illuminate/support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet('blade.compil in /home/.../core/vendor/illuminate/container/Container.php on line 806
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255
```

**Comment by sashabeep** [comment]
С https://github.com/evolution-cms/evolution/commit/6872583bc9f7decda44e1ae61ebf6dd872509fe1 результат такой же

**Comment by ZeeyN** [comment]
@sashabeep Что я выяснил: на данный момент в 2.0.2 сломаны директивы, которые вызываются из провайдера, пакет версии 1.2.0 работает на директивах. Рекомендую устанавливать предыдущие версии до момента исправления баги в cms-ке.

**Comment by sashabeep** [comment]
@ZeeyN при обновлениии так или иначе нужно выполнить composer update. Как нужно модифицировать composer.json в custom чтобы пакет не апнулся при этом?

Ну и для экстренных случаев хотелось бы знать, как стереть вручную

**Comment by ZeeyN** [comment]
@sashabeep  строго прописать "1.1.*" так должно подгрузить последнюю версию пакета без директив

**Comment by sashabeep** [comment]
Как вручную удалить пакет?
Где и какие файлы переписать

**Comment by ZeeyN** [comment]
В **core/composer.json** найти сам пакет, удалить запись о нём из файла, после прописать в консоли `composer update`, если будет после данных операций выскакивать ошибка, то в **core/custom/config/app/providers/** удалить файл **MinifierServiceProvider.php**

Если записи нет в **core/composer.json**, то она в **core/custom/packages/composer.json**
